### ISSUE TITLE
Propose to move this project to official organization for terraform-docs

### ISSUE THREAD

**Issue by khos2ow** [Dirrk/terraform-docs#24]
We've recently moved `terraform-docs` to its own organization, https://github.com/terraform-docs/. I would like to see what you think about migrating this project to that organization too? It will give our users a central place for all the toolings and projects surrounding `terraform-docs`?

I think we would have two options, 1) completely move this repo 2) fork this repo under official org and mark this repo as archived, for future visibility and may be current user of this action.

**Comment by khos2ow** [comment]
@Dirrk any update on this?

**Comment by Dirrk** [comment]
@khos2ow I am fine with moving it over

**Comment by albertrdixon** [comment]
+1 for fork and archive if this is still proceeding. We make good use of this action and keeping this repo around would ease our transition.

**Comment by ForsakenHarmony** [comment]
@Dirrk please archive the repo and add a link to the readme

**Comment by khos2ow** [comment]
I'd like that action name is also renamed to, e.g. `terraform-docs-deprecated` or something ([here](https://github.com/Dirrk/terraform-docs/blob/master/action.yml#L1)), so we can use `terraform-docs` as action name for https://github.com/marketplace/actions/terraform-docs-gh-actions.
