### ISSUE TITLE
upgrade to terraform-docs version to at least 0.10.0

### ISSUE THREAD

**Issue by clear-ryan** [Dirrk/terraform-docs#26]
The latest version has the capability to use a config file when generating terraform docs.

**Comment by clear-ryan** [comment]
I created https://github.com/Dirrk/terraform-docs/pull/27 to update the tf-docs version

**Comment by fatbasstard** [comment]
Please update to 0.13.0 for the TF 0.15 support: https://github.com/terraform-docs/terraform-docs/releases/tag/v0.13.0

**Comment by ev1lm0nk3y** [comment]
@fatbasstard I've made the update to my PR, though I'm not exactly sure if anyone is monitoring this repo anymore

**Comment by clear-ryan** [comment]
@fatbasstard I've made the updates to my PR, but I don't think anyone is watching this repo anymore.

**Comment by Dirrk** [comment]
This repository is being deprecated please use https://github.com/terraform-docs/gh-actions
